apiVersion: v1
kind: Service
metadata:
  name: usermgmt-webapp-service
  namespace: app-with-pvc
  labels: 
    app: usermgmt-webapp
spec: 
  type: NodePort  # Changed from LoadBalancer to NodePort
  selector: 
    app: usermgmt-webapp
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 30040  # Add this line to specify the node port (30000-32767 range)
