apiVersion: v1
kind: Service
metadata:
  name: windows-app-service
  namespace: windows-app
spec:
  selector:
    app: windows-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30007  # NodePort range: 30000-32767
