apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ici-premium-disk
parameters:
  skuname: Premium_LRS              # Premium SSD
provisioner: disk.csi.azure.com     # Azure managed disk
reclaimPolicy: Delete              
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true        # Allow volume expansion so that if required more storage space can be provisioned on the same PV